#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd


# In[2]:


dataset = pd.read_csv("Social_Network_Ads.csv")


# In[4]:


dataset.head()


# In[5]:


dataset.columns


# In[6]:


dataset[['Age']]


# In[7]:


X = dataset[['Age', 'EstimatedSalary' ] ] 


# In[8]:


y = dataset['Purchased']


# In[9]:


type(X)


# In[10]:


X = X.values


# In[11]:


type(X)


# In[12]:


y = y.values


# In[13]:


type(y)


# In[14]:


